### PR TITLE
Bug/Do not replace caller-supplied VRs with UN for unknown Tags

### LINKED ISSUE #193: Bug: Write() replaces all VRs for unknown tags with 'UN'
Hello,

I came across another Write() bug today. Currently with the way VRs are checked, if an element's tag is not known (i.e., it isn't contained in our tag dict), Write() falls back to using 'UN' as the VR for the element:

```go
func verifyVROrDefault(t tag.Tag, vr string, opts writeOptSet) (string, error) {
	tagInfo, err := tag.Find(t)
	if err != nil {
		return vrraw.Unknown, nil
	}
	// logic continues
```

This causes issues with Private Element encoded with an Explicit Transfer Syntax. Since the Private element's VR's are known, Write() should keep them in-place when re-writing a file. Instead, all Private elements are encoded with 'UN'. Which can also trigger type errors elsewhere. I originally discovered this when I got the following error when encoding Private elements:

```
error writing DICOM: ValueType does not match the VR required
```

I'm working for a PR on this that I'll post shortly.

### PR DESCRIPTION
**Pull request by bpeake-illuscio**
Hello!

This PR closes #193 .

This PR changes the behavior of the writer to default to any existing VR value when we do not have any information on the tag, effectively trusting that the caller knows more than we do about this element. I've added a couple tests to verify this is working as intended, and I've also refactored the logic a bit in `verifyVROrDefault` and added some code comments explaining the intent of certain logic paths.

### CODE REVIEW

File: write.go [hunk 1]
```diff
@@ -188,6 +188,7 @@ func writeElement(w dicomio.Writer, elem *Element, opts writeOptSet) error {
 		return err
 	}
 
+	w.GetTransferSyntax()
```
Comment (suyashkumar) [inline write.go:191]: can you tell me more about why this is needed?

**Review by suyashkumar — APPROVED** [review]
Thanks @bpeake-illuscio, I think this makes sense! Generally LGTM, but had one question. 

Also apologies for the delay--I should be more active this month (had several things going on before).

File: write.go (hunk 1 above)
Comment (bpeake-illuscio) [reply write.go]: Whoops, having some logic there, then removed it in a refactor and missed that line, thanks for the catch!
